### ISSUE TITLE
KeyError: 'starburst'

### ISSUE THREAD

**Issue by mschart** [AllenInstitute/allensdk.eye_tracking#38]
I'd like to try your mouse eye-tracker but I get errors (on Ubuntu 17.10, python 2.7):

I created a new anaconda environment, installed the dependencies

```
conda install scikit-image
conda install pyqt
conda install -c conda-forge opencv
```

and the developper version of the AllenSDK Eye Tracking.

I have a close up video of a mouse eye and try to apply your software to it:

```
> (allen) mic@mic-OptiPlex-9010:~$ allensdk.eye_tracking --input_source '/home/mic/Videos/IBL_videos/eye_cropped2.mp4'
> Traceback (most recent call last):
>   File "/home/mic/anaconda2/envs/allen/bin/allensdk.eye_tracking", line 11, in <module>
>     load_entry_point('allensdk-eye-tracking==1.2.0', 'console_scripts', 'allensdk.eye_tracking')()
>   File "/home/mic/anaconda2/envs/allen/lib/python3.6/site-packages/allensdk/eye_tracking/__main__.py", line 98, in main
>     starburst_args = get_starburst_args(mod.args["starburst"])
> KeyError: 'starburst'
```

**Comment by JFPerkins** [comment]
@mschart his should now be fixed on dev. Please be aware that I've updated installation instructions slightly as a recent update to the conda-forge channel's opencv breaks compatibility with pyqt from default. The updated instructions specify a new channel to install pyqt from.
