### ISSUE TITLE
cv2.error:_img.size().height function matchTemplate

### ISSUE THREAD

**Issue by mschart** [AllenInstitute/allensdk.eye_tracking#40]
Hi there,
I get an error with respect to video dimensions. Here is how I installed allensdk.eye_tracking on Ubuntu 17.10:

```
~$ conda create --name allen
~$ source activate allen
~$ python
Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct 13 2017, 10:47:14) 
[GCC 7.2.0] on linux2
~$ conda install scikit-image
~$ conda install pyqt
~$ conda install -c conda-forge opencv
~$ cd allensdk.eye_tracking-dev/
~/allensdk.eye_tracking-dev$ pip install .
~/allensdk.eye_tracking-dev$ allensdk.eye_tracking --input_source '/home/mic/Videos/IBL_videos/eye_cropped.mp4'
OpenCV(3.4.1) Error: Assertion failed (_img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width) in matchTemplate, file /feedstock_root/build_artefacts/opencv_1520722599420/work/opencv-3.4.1/modules/imgproc/src/templmatch.cpp, line 1107
Traceback (most recent call last):
  File "/home/mic/anaconda2/envs/allen/bin/allensdk.eye_tracking", line 11, in <module>
    load_entry_point('allensdk-eye-tracking==1.2.0', 'console_scripts', 'allensdk.eye_tracking')()
  File "/home/mic/anaconda2/envs/allen/lib/python3.6/site-packages/allensdk/eye_tracking/__main__.py", line 123, in main
    step=mod.args.get("frame_step", 1)
  File "/home/mic/anaconda2/envs/allen/lib/python3.6/site-packages/allensdk/eye_tracking/eye_tracking.py", line 649, in process_stream
    self.process_image(frame)
  File "/home/mic/anaconda2/envs/allen/lib/python3.6/site-packages/allensdk/eye_tracking/eye_tracking.py", line 590, in process_image
    pupil_parameters, pupil_error = self.find_pupil(cr_parameters)
  File "/home/mic/anaconda2/envs/allen/lib/python3.6/site-packages/allensdk/eye_tracking/eye_tracking.py", line 506, in find_pupil
    self.pupil_bounding_box, reject_coords=reject)
  File "/home/mic/anaconda2/envs/allen/lib/python3.6/site-packages/allensdk/eye_tracking/feature_extraction.py", line 70, in max_correlation_positions
    cv2.TM_CCORR_NORMED)
cv2.error: OpenCV(3.4.1) /feedstock_root/build_artefacts/opencv_1520722599420/work/opencv-3.4.1/modules/imgproc/src/templmatch.cpp:1107: error: (-215) _img.size().height <= _templ.size().height && _img.size().width <= _templ.size().width in function matchTemplate
```
Here is some video info about the mouse eye mp4 video:

![image](https://user-images.githubusercontent.com/17218515/38488385-98fad3f8-3be3-11e8-875e-23c8247e3030.png)

Looks like that:

![image](https://user-images.githubusercontent.com/17218515/38488406-a7201272-3be3-11e8-8061-b656fa01bec5.png)

Many thanks for your help!

**Comment by JFPerkins** [comment]
It looks like your images are much smaller than what the Institute uses, small enough in fact that the default template size for the pupil is larger than one of the dimensions of your image. This likely means that a whole bunch of the default parameters are not going to work for your video. 

Try:

    allensdk.eye_tracking --input_source '/home/mic/Videos/IBL_videos/eye_cropped.mp4' --eye_params.pupil_mask_radius 5 --eye_params.cr_mask_radius 5 --starburst.threshold_pixels 5

**Comment by mschart** [comment]
Hi Jed, Many thanks, this seemed to have worked now:

```
(allen) mic@mic-OptiPlex-9010:~/allensdk.eye_tracking-dev$ allensdk.eye_tracking --input_source '/home/mic/Videos/IBL_videos/eye_cropped.mp4' --eye_params.pupil_mask_radius 5 --eye_params.cr_mask_radius 5 --starburst.threshold_pixels 5
{
 "input_parameters": {
  "starburst": {
   "threshold_pixels": 5,
   "threshold_factor": 1.2,
   "n_rays": 150,
   "index_length": 150
  },
  "pupil_bounding_box": [],
  "log_level": "ERROR",
  "input_source": "/home/mic/Videos/IBL_videos/eye_cropped.mp4",
  "eye_params": {
   "smoothing_kernel_size": 7,
   "average_iris_intensity": 40,
   "adaptive_pupil": false,
   "clip_pupil_values": true,
   "max_eccentricity": 0.25,
   "pupil_mask_radius": 5,
   "cr_mask_radius": 5,
   "min_pupil_value": 0,
   "recolor_cr": true,
   "max_pupil_value": 30,
   "cr_recolor_scale_factor": 1.7
  },
  "output_dir": "./",
  "cr_bounding_box": []
 },
 "pupil_parameter_file": "./pupil_params.npy",
 "module_version": "1.2.0",
 "mean_frame_file": "./mean_frame.png",
 "cr_parameter_file": "./cr_params.npy"
}
```

Is there a way to overlay the fitted ellipse on top of the video to check how well it did?

**Comment by mschart** [comment]
I'd be great if you could provide some example (video and parameter settings) to illustrate how to evaluate the tracking. Cheers

**Comment by JFPerkins** [comment]
The 5 values are (x, y, rotation, minor, major). All NaN means it didn't fit the pupil. You can visualize the output by configuring the `annotation` settings. `allensdk.eye_tracking --help` to see the parameters you can change.

**Comment by mschart** [comment]
I have tried another video with higher spatial resolution (200 × 176, 120fps), using these params
`--eye_params.pupil_mask_radius 5 --eye_params.cr_mask_radius 5 --starburst.threshold_pixels 5`
but still finding all pupil params to be nan. Is there a way to pick these parameters in a principled way given one example frame of the video?

**Comment by JFPerkins** [comment]
You can specify a bounding box for the pupil with --pupil_bounding_box [xmin,xmax,ymin,ymax], where the origin is the top left of the image. Yes, `cr_params` is fitting the white reflection blob.

**Comment by mschart** [comment]
Great, thanks. What video resolution do you guys use?

**Comment by JFPerkins** [comment]
Sorry for the delayed response. Our eye tracking videos are 640x480.
